# Generated by Django 5.0.3 on 2024-06-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('time_to_generate_answer', models.DurationField()),
                ('question_timestamp', models.DateTimeField()),
            ],
        ),
    ]
